{{- if .Values.secretProviderClass.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "Helm-Chart.fullname" . }}
spec:
  provider: azure
  secretObjects:
  - secretName: {{ .Values.secretProviderClass.secretObjects.secretName }}
    type: kubernetes.io/tls
    data:
    {{- range .Values.secretProviderClass.secretObjects.data }}
    - objectName: {{ .objectName}}
      key: {{ .key }}
    {{- end}}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.secretProviderClass.aksKvCsiProviderID }}
    keyvaultName: {{ .Values.secretProviderClass.keyvaultName }}
    objects: |
      array:
        {{- range .Values.secretProviderClass.secrets }}
        - |
          objectName: {{ .name }}
          objectType: {{ .type }}
        {{- end }}
    resourceGroup: {{ .Values.secretProviderClass.resourceGroup }}
    subscriptionId: {{ .Values.secretProviderClass.subscriptionId }}
    tenantId: {{ .Values.secretProviderClass.tenantId }}
{{- end }}